### ISSUE TITLE
Sync Not Started From Sub-directory

### ISSUE THREAD

**Issue by tylersatre** [francoisvdv/lando-mutagen#115]
If `lando start` is run from a sub-directory the container starts up as expected, but the sync does not start.  Example:

```
project
│   .lando.yml 
│
└───folder1
│   │   file011.txt
│   │   file012.txt
│   │
│   └───subfolder1
│       │   file111.txt
│       │   file112.txt
```

Running `lando start` in the `project` directory starts the sync.  If it is run from `project/folder1` or `project/folder1/subfolder1` the container will start, but the sync will not.  I know that the `lando` command will go up directories to find a `.lando.yml` file to use for configuration, it seems like this plugin isn't doing that.

**Comment by francoisvdv** [comment]
Fix released in [v1.0.12](https://github.com/francoisvdv/lando-mutagen/releases/tag/v1.0.12)
