### ISSUE TITLE
Error: invalid synchronization session name (node_modules): invalid name character at index 16: '_'

### ISSUE THREAD

**Issue by felipereisdev** [francoisvdv/lando-mutagen#28]
Hello. First I would like to thank you for this plugin from lando. Well, I've come across this error in folders with the underscore symbol. The example of the error is the folder named node_modules.

**Comment by francoisvdv** [comment]
Thanks! This should be an easy enough fix, I'll look into it.

**Comment by francoisvdv** [comment]
Fixed in https://github.com/francoisvdv/lando-mutagen/blob/main/CHANGELOG.md#108-2022-03-28, could you verify this works for you?

**Comment by felipereisdev** [comment]
> Fixed in [1.0.8](https://github.com/francoisvdv/lando-mutagen/blob/main/CHANGELOG.md#108-2022-03-28), could you verify this works for you?

It's working. Thank you and I also appreciate the speed in solving the problem.

**Comment by francoisvdv** [comment]
Great, thanks for the feedback!
