### ISSUE TITLE
'which' is not available on Windows

### ISSUE THREAD

**Issue by KeyvanE** [francoisvdv/lando-mutagen#39]
https://github.com/francoisvdv/lando-mutagen/blob/4423e0e299f521ba5baca83678d5c87232600c57/src/Mutagen.ts#L22

An equivalent is "where.exe" (the .exe is important)

![image](https://user-images.githubusercontent.com/5048761/163104392-1d9263cd-af76-4ca6-9d2e-fba479dc31fb.png)

**Comment by francoisvdv** [comment]
Hi, I added this fix in v1.0.9, but as I do not have a Windows machine available right now I cannot test this. Could you try and verify if it works? For now I will close this issue but it can be reopened if it is found to not work.
